services:
  # Backend API service
  - type: web
    name: auterion-drone-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: AUTERION_API_TOKEN
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://auterion-drone.onrender.com

  # Frontend React application
  - type: web
    name: auterion-drone
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        value: https://auterion-drone-api.onrender.com
      - key: REACT_APP_AUTERION_API_TOKEN
        sync: false